spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/micro-services"
  config:
    import: optional:configserver:http://localhost:8787
  application:
    name: gateway-service
